---
kind: pipeline
type: docker
name: default
steps:
  - name: autotag
    image: nightfuryest/drone-plugin-package-auto-tag
    settings:
      git_user:
        from_secret: git_auto_tag_user
      git_token:
        from_secret: git_auto_tag_token
      dry_run: false
  - name: Build Packages
    image: nightfuryest/drone-downstream
    settings:
      drone_server: https://github.drone.vicoders.com
      drone_token:
        from_secret: webpress_vn_org_drone_secret
      params:
        - PACKAGE_NAME=${DRONE_REPO}
        - PACKAGE_VERSION=${DRONE_TAG}
      repositories:
        - webpress-core/packages.webpress.vn
trigger:
  event:
    - tag
